// Package store persists vrs repositories: a single SQLite database per repo
// holding snapshots, manifests, content-addressed chunks, the oplog and the
// working-copy cache.
package store

import (
	"database/sql"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"time"

	"github.com/justinkadima/vrs/internal/snap"
	_ "modernc.org/sqlite"
)

const dbFile = "vrs.db"

const schema = `
CREATE TABLE IF NOT EXISTS meta (
  key   TEXT PRIMARY KEY,
  value TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS snapshots (
  id      INTEGER PRIMARY KEY,
  ts      INTEGER NOT NULL,
  kind    TEXT NOT NULL,             -- 'save' | 'capture' (hidden from log)
  message TEXT,
  parent  INTEGER
);
CREATE TABLE IF NOT EXISTS entries (
  snapshot  INTEGER NOT NULL REFERENCES snapshots(id),
  path      TEXT NOT NULL,
  file_hash TEXT NOT NULL,
  size      INTEGER NOT NULL,
  mode      INTEGER NOT NULL,
  PRIMARY KEY (snapshot, path)
) WITHOUT ROWID;
CREATE TABLE IF NOT EXISTS chunks (
  hash     TEXT PRIMARY KEY,
  data     BLOB NOT NULL,
  raw_size INTEGER NOT NULL,
  refcount INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS file_chunks (
  file_hash  TEXT NOT NULL,
  seq        INTEGER NOT NULL,
  chunk_hash TEXT NOT NULL,
  PRIMARY KEY (file_hash, seq)
) WITHOUT ROWID;
CREATE TABLE IF NOT EXISTS ops (
  id     INTEGER PRIMARY KEY,
  ts     INTEGER NOT NULL,
  kind   TEXT NOT NULL,
  detail TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS redo_stack (
  id      INTEGER PRIMARY KEY,       -- top = max(id)
  capture INTEGER NOT NULL,
  target  INTEGER NOT NULL,
  scope   TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS wc_cache (
  path      TEXT PRIMARY KEY,
  mtime_ns  INTEGER NOT NULL,
  size      INTEGER NOT NULL,
  file_hash TEXT NOT NULL
);
`

const defaultIgnoreFile = `# vrs ignore patterns — gitignore syntax.
# Built-in defaults always apply (re-include with a !pattern below):
#   node_modules/  .git/  target/  dist/  build/  out/  __pycache__/
#   .venv/  venv/  .DS_Store  *.pyc  .env*
`

// Store is the persistence layer of one repository.
type Store struct {
	db   *sql.DB
	root string
}

func DBPath(root string) string { return filepath.Join(root, ".vrs", dbFile) }

// Open opens the database of an existing repository.
func Open(root string) (*Store, error) {
	if _, err := os.Stat(DBPath(root)); err != nil {
		return nil, fmt.Errorf("not a vrs repository: %s", root)
	}
	return openDB(root)
}

// openDB opens (creating if needed) the repository database.
func openDB(root string) (*Store, error) {
	db, err := sql.Open("sqlite", DBPath(root))
	if err != nil {
		return nil, err
	}
	db.SetMaxOpenConns(1)
	s := &Store{db: db, root: root}
	if err := s.pragmas(); err != nil {
		db.Close()
		return nil, err
	}
	return s, nil
}

func (s *Store) Close() error { return s.db.Close() }

func (s *Store) pragmas() error {
	for _, p := range []string{
		"PRAGMA busy_timeout = 5000",
		"PRAGMA journal_mode = WAL",
		"PRAGMA synchronous = NORMAL",
		"PRAGMA auto_vacuum = INCREMENTAL",
		"PRAGMA foreign_keys = ON",
	} {
		if _, err := s.db.Exec(p); err != nil {
			return fmt.Errorf("pragma %q: %w", p, err)
		}
	}
	return nil
}

// InitAt creates a new repository rooted at dir. chunkerPolyHex is the chunker
// polynomial (hex) generated by the caller and pinned in the repo's metadata.
func InitAt(dir, chunkerPolyHex string) (*Store, error) {
	vrsDir := filepath.Join(dir, ".vrs")
	if _, err := os.Stat(vrsDir); err == nil {
		return nil, fmt.Errorf("already a vrs repository: %s", dir)
	}
	if err := os.MkdirAll(filepath.Join(vrsDir, "trash"), 0o755); err != nil {
		return nil, err
	}
	igPath := filepath.Join(dir, ".vrsignore")
	if _, err := os.Stat(igPath); os.IsNotExist(err) {
		if err := os.WriteFile(igPath, []byte(defaultIgnoreFile), 0o644); err != nil {
			return nil, err
		}
	}
	s, err := openDB(dir)
	if err != nil {
		return nil, err
	}
	if _, err := s.db.Exec(schema); err != nil {
		s.Close()
		return nil, fmt.Errorf("create schema: %w", err)
	}
	sets := [][2]string{
		{"schema_version", "1"},
		{"chunker_poly", chunkerPolyHex},
		{"base", "0"},
		{"created", strconv.FormatInt(time.Now().UnixNano(), 10)},
	}
	for _, kv := range sets {
		if err := s.setMeta(kv[0], kv[1]); err != nil {
			s.Close()
			return nil, err
		}
	}
	return s, nil
}

// --- meta -----------------------------------------------------------------

func (s *Store) setMeta(key, value string) error {
	_, err := s.db.Exec(
		"INSERT INTO meta (key, value) VALUES (?, ?) ON CONFLICT(key) DO UPDATE SET value = excluded.value",
		key, value)
	return err
}

// Meta returns a repository metadata value.
func (s *Store) Meta(key string) (string, error) {
	var v string
	err := s.db.QueryRow("SELECT value FROM meta WHERE key = ?", key).Scan(&v)
	return v, err
}

// Base returns the snapshot id the working copy currently sits on (0 = none).
func (s *Store) Base() (int64, error) {
	v, err := s.Meta("base")
	if err != nil {
		return 0, err
	}
	n, err := strconv.ParseInt(v, 10, 64)
	if err != nil {
		return 0, fmt.Errorf("bad base value %q", v)
	}
	return n, nil
}

// --- reads ----------------------------------------------------------------

// LoadCache returns the working-copy fast-path cache.
func (s *Store) LoadCache() (map[string]snap.CacheEntry, error) {
	rows, err := s.db.Query("SELECT path, mtime_ns, size, file_hash FROM wc_cache")
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	m := make(map[string]snap.CacheEntry)
	for rows.Next() {
		var path, hash string
		var c snap.CacheEntry
		if err := rows.Scan(&path, &c.MtimeNS, &c.Size, &hash); err != nil {
			return nil, err
		}
		c.Hash = hash
		m[path] = c
	}
	return m, rows.Err()
}

// ParentEntries returns a snapshot's manifest as a path-keyed map.
func (s *Store) ParentEntries(id int64) (map[string]snap.Prev, error) {
	rows, err := s.db.Query(
		"SELECT path, file_hash, size, mode FROM entries WHERE snapshot = ?", id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	m := make(map[string]snap.Prev)
	for rows.Next() {
		var p string
		var prev snap.Prev
		if err := rows.Scan(&p, &prev.Hash, &prev.Size, &prev.Mode); err != nil {
			return nil, err
		}
		m[p] = prev
	}
	return m, rows.Err()
}

// SnapRow is one timeline row.
type SnapRow struct {
	ID      int64
	TS      int64
	Kind    string
	Message string
}

// ListSnapshots lists the timeline, newest first. When all is false, only
// user-visible 'save' snapshots are returned.
func (s *Store) ListSnapshots(all bool, limit int) ([]SnapRow, error) {
	q := "SELECT id, ts, kind, COALESCE(message, '') FROM snapshots"
	if !all {
		q += " WHERE kind = 'save'"
	}
	q += " ORDER BY id DESC"
	if limit > 0 {
		q += " LIMIT " + strconv.Itoa(limit)
	}
	rows, err := s.db.Query(q)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []SnapRow
	for rows.Next() {
		var r SnapRow
		if err := rows.Scan(&r.ID, &r.TS, &r.Kind, &r.Message); err != nil {
			return nil, err
		}
		out = append(out, r)
	}
	return out, rows.Err()
}

// --- writes ---------------------------------------------------------------

// SaveInfo reports what a Save did.
type SaveInfo struct {
	ID        int64
	NewRaw    int64 // bytes of new (uncompressed) chunk content stored
	NewStored int64 // bytes actually stored after compression
}

// Save writes a capture result as a new snapshot in one transaction:
// snapshot row, manifest entries, new chunks (deduplicated), file versions,
// working-copy cache, base pointer and oplog entry.
func (s *Store) Save(res *snap.CaptureResult, message, kind string, parent int64) (*SaveInfo, error) {
	tx, err := s.db.Begin()
	if err != nil {
		return nil, err
	}
	defer tx.Rollback() // no-op after commit

	ts := time.Now().UnixNano()
	var parentArg any
	if parent > 0 {
		parentArg = parent
	}
	r, err := tx.Exec(
		"INSERT INTO snapshots (ts, kind, message, parent) VALUES (?, ?, ?, ?)",
		ts, kind, message, parentArg)
	if err != nil {
		return nil, err
	}
	id, err := r.LastInsertId()
	if err != nil {
		return nil, err
	}
	info := &SaveInfo{ID: id}

	eStmt, err := tx.Prepare("INSERT INTO entries (snapshot, path, file_hash, size, mode) VALUES (?, ?, ?, ?, ?)")
	if err != nil {
		return nil, err
	}
	defer eStmt.Close()
	for _, e := range res.Entries {
		if _, err := eStmt.Exec(id, e.Path, e.Hash, e.Size, e.Mode); err != nil {
			return nil, err
		}
	}

	// Register content versions and their chunks. Versions already known
	// (same content seen in an earlier snapshot) are skipped entirely.
	for _, v := range res.Versions {
		var known string
		err := tx.QueryRow("SELECT file_hash FROM file_chunks WHERE file_hash = ? LIMIT 1", v.FileHash).Scan(&known)
		if err == nil {
			continue
		}
		if err != sql.ErrNoRows {
			return nil, err
		}
		for i, c := range v.Chunks {
			cr, err := tx.Exec(
				"INSERT OR IGNORE INTO chunks (hash, data, raw_size, refcount) VALUES (?, ?, ?, 0)",
				c.Hash, c.Data, c.RawSize)
			if err != nil {
				return nil, err
			}
			if aff, err := cr.RowsAffected(); err == nil && aff > 0 {
				info.NewRaw += c.RawSize
				info.NewStored += int64(len(c.Data))
			}
			if _, err := tx.Exec("UPDATE chunks SET refcount = refcount + 1 WHERE hash = ?", c.Hash); err != nil {
				return nil, err
			}
			if _, err := tx.Exec(
				"INSERT INTO file_chunks (file_hash, seq, chunk_hash) VALUES (?, ?, ?)",
				v.FileHash, i, c.Hash); err != nil {
				return nil, err
			}
		}
	}

	wStmt, err := tx.Prepare(`INSERT INTO wc_cache (path, mtime_ns, size, file_hash) VALUES (?, ?, ?, ?)
		ON CONFLICT(path) DO UPDATE SET mtime_ns=excluded.mtime_ns, size=excluded.size, file_hash=excluded.file_hash`)
	if err != nil {
		return nil, err
	}
	defer wStmt.Close()
	for _, e := range res.Entries {
		if _, err := wStmt.Exec(e.Path, e.MtimeNS, e.Size, e.Hash); err != nil {
			return nil, err
		}
	}
	if _, err := tx.Exec("DELETE FROM wc_cache WHERE path NOT IN (SELECT path FROM entries WHERE snapshot = ?)", id); err != nil {
		return nil, err
	}

	if _, err := tx.Exec(
		"INSERT INTO meta (key, value) VALUES ('base', ?) ON CONFLICT(key) DO UPDATE SET value = excluded.value",
		strconv.FormatInt(id, 10)); err != nil {
		return nil, err
	}

	detail, err := json.Marshal(map[string]any{"snapshot": id, "files": len(res.Entries)})
	if err != nil {
		return nil, err
	}
	if _, err := tx.Exec("INSERT INTO ops (ts, kind, detail) VALUES (?, ?, ?)", ts, kind, detail); err != nil {
		return nil, err
	}

	if err := tx.Commit(); err != nil {
		return nil, err
	}
	return info, nil
}
